# Site settings
title: "Stories by Tom"
email: ""
description: "Dinge, die mich bewegen - festgehalten in Bildern und Notizen."
minimal_mistakes_skin: "default"
search: true

url: "https://storiesbytom.com"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.28.1"

# Outputting
permalink: /:categories/:title/
paginate: 4
paginate_path: /page:num/

# WICHTIG: Kein include von _pages mehr!
include:
  - _data

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Settings
author:
  name: "Tom Stelzer"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Dinge, die mich bewegen - festgehalten in Bildern und Notizen."
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/stories.by.tom/"
    - label: "E-Mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:stelzer.tom93@gmail.com"

# Collections
collections:
  einblicke:
    output: true
    permalink: /einblicke/:path/
  projekte:
    output: true
    permalink: /projekte/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _einblicke
  - scope:
      path: ""
      type: einblicke
    values:
      layout: single
      author_profile: false
  # _projekte
  - scope:
      path: ""
      type: projekte
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "posts"
    values:
      header:
        teaser: /assets/images/default-teaser.jpg # Pfad zu einem neutralen Standard-Bild

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
